name: build utils

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    type: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
